### ISSUE TITLE
jsnext:main

### ISSUE THREAD

**Issue by Qard** [bokuweb/re-bulma#23]
You should consider including `src` in the `npm publish` and using the `jsnext:main` field so ES6 module loaders like rollup can find the ES6 code and do tree-shaking before bundling. You can get much smaller builds than webpack or browserify that way. 😸

**Comment by bokuweb** [comment]
@Qard thanks!! I’ll give it a try.

**Comment by Qard** [comment]
Here's some info on it: https://github.com/rollup/rollup/wiki/jsnext:main
