### ISSUE TITLE
Using in React-Native

### ISSUE THREAD

**Issue by infacq** [bokuweb/re-bulma#42]
I failed to use this in my experiment with `react-native`. Is there any specific configuration? Here is the error that I encounter

<img width="373" alt="screen shot 2016-08-12 at 3 01 32 pm" src="https://cloud.githubusercontent.com/assets/1596891/17615028/b053f520-609d-11e6-8338-48d58be67f21.png">

**Comment by bokuweb** [comment]
@infaq Sorry. react-native is not supported
