### ISSUE TITLE
Using server side rendering, "document is not defined" error

### ISSUE THREAD

**Issue by dokenzy** [bokuweb/re-bulma#47]
In my server side rendering app, I have come across this error:

```
project/node_modules/insert-css/index.js:7
    var elem = document.createElement('style');
```

I just wrote: `import { Container } from 're-bulma';`

How can I use re-bulma with SSR?

**Comment by bokuweb** [comment]
@dokenzy Sorry for my late reply. I think, It is necessary to not insert styles  when SSR.

fix this line https://github.com/bokuweb/re-bulma/blob/8d1fe7ce7d931e2b47d0ea23e1e3fe2b55742133/src/index.js#L87

```
if (document) insertCss(css, { prepend: true });
```
