### ISSUE TITLE
Incorrect use of the `module` field for ES2015 module-support

### ISSUE THREAD

**Issue by eltonjuan** [bokuweb/re-bulma#72]
Added with this commit aee8cbc9ec1a0bf8d64121750fc2f0cc0e4b97a2 , it seems that re-bulma is incorrectly using the `module` field in `package.json`. Using webpack2, re-bulma is failing to build because the `module` field is pointing to `src/index.js` which is a file that requires transpilation. 

Correct me if I'm wrong, but all of my research on the topic leads me to believe that the `module` field should still be built & transpiled, leaving only the ES2015 module syntax in tact (i.e. `import` and `export` are okay, but as a consumer we still need you to transpile / build your code). If you look at [`redux`](https://www.github.com/gaearon/redux), they have a build step that transpiles their code using `babel`, but leaves the es6 module syntax in place.

**Comment by eltonjuan** [comment]
@capaj I noticed you committed the original change, am I correct in my assessment?

**Comment by capaj** [comment]
Yes it should be built to be es2015 compatible.re-bulma also uses jsx and stage-1 so we're definitely missing a build step there. Will try to open a fixing PR.

**Comment by capaj** [comment]
@eltonjuan fixing PR here: #74

**Comment by eltonjuan** [comment]
Thanks for the quick turnaround! 👍
